# Generated by Django 6.1.1 on 2026-09-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_pagesection_section_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.URLField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3059.5710802923595!2d-82.87773729999999!3d39.928613899999995!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x883862ccfccdfc75%3A0x949505a676e6f524!2s2242%20S%20Hamilton%20Rd%20%23208%2C%20Columbus%2C%20OH%2043232%2C%20USA!5e0!3m2!1sen!2sph!4v1747174671756!5m2!1sen!2sph', max_length=1000),
        ),
    ]
