# Generated by Django 6.1.1 on 2026-09-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_sitesettings_map_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='invitation_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='password_set',
            field=models.BooleanField(default=True),
        ),
    ]
