# Generated by Django 6.1.1 on 2026-09-17 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_adminprofile_invitation_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.mediaitem'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='anchor_id',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
