# Generated by Django 6.1.1 on 2026-09-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_navigationitem_icon_pagesection_anchor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
